// Banco de patógenos humanos comuns
// { name, commonName, category }

export const PATHOGEN_DB = [
  // ── Fungi ─────────────────────────────────────────────────────────────────
  { name: "Aspergillus fumigatus",          commonName: "Aspergilose invasiva",          category: "fungi" },
  { name: "Aspergillus flavus",             commonName: "Aspergilose",                   category: "fungi" },
  { name: "Aspergillus niger",              commonName: "Aspergilose / Otomicose",        category: "fungi" },
  { name: "Aspergillus terreus",            commonName: "Aspergilose",                   category: "fungi" },
  { name: "Candida albicans",               commonName: "Candidíase",                    category: "fungi" },
  { name: "Candida glabrata",               commonName: "Candidíase",                    category: "fungi" },
  { name: "Candida tropicalis",             commonName: "Candidíase",                    category: "fungi" },
  { name: "Candida parapsilosis",           commonName: "Candidíase",                    category: "fungi" },
  { name: "Candida krusei",                 commonName: "Candidíase",                    category: "fungi" },
  { name: "Candida auris",                  commonName: "Candidíase multirresistente",   category: "fungi" },
  { name: "Cryptococcus neoformans",        commonName: "Criptococose",                  category: "fungi" },
  { name: "Cryptococcus gattii",            commonName: "Criptococose",                  category: "fungi" },
  { name: "Histoplasma capsulatum",         commonName: "Histoplasmose",                 category: "fungi" },
  { name: "Blastomyces dermatitidis",       commonName: "Blastomicose",                  category: "fungi" },
  { name: "Coccidioides immitis",           commonName: "Coccidioidomicose",             category: "fungi" },
  { name: "Coccidioides posadasii",         commonName: "Coccidioidomicose",             category: "fungi" },
  { name: "Paracoccidioides brasiliensis",  commonName: "Paracoccidioidomicose",         category: "fungi" },
  { name: "Paracoccidioides lutzii",        commonName: "Paracoccidioidomicose",         category: "fungi" },
  { name: "Sporothrix schenckii",           commonName: "Esporotricose",                 category: "fungi" },
  { name: "Sporothrix brasiliensis",        commonName: "Esporotricose",                 category: "fungi" },
  { name: "Pneumocystis jirovecii",         commonName: "Pneumocistose",                 category: "fungi" },
  { name: "Talaromyces marneffei",          commonName: "Talaromicose",                  category: "fungi" },
  { name: "Mucor spp.",                     commonName: "Mucormicose",                   category: "fungi" },
  { name: "Rhizopus spp.",                  commonName: "Mucormicose",                   category: "fungi" },
  { name: "Lichtheimia corymbifera",        commonName: "Mucormicose",                   category: "fungi" },
  { name: "Cunninghamella bertholletiae",   commonName: "Mucormicose",                   category: "fungi" },
  { name: "Fusarium solani",                commonName: "Fusariose",                     category: "fungi" },
  { name: "Fusarium oxysporum",             commonName: "Fusariose",                     category: "fungi" },
  { name: "Scedosporium apiospermum",       commonName: "Escedosporiose",                category: "fungi" },
  { name: "Lomentospora prolificans",       commonName: "Lomentosporiose",               category: "fungi" },
  { name: "Fonsecaea pedrosoi",             commonName: "Cromoblastomicose",             category: "fungi" },
  { name: "Phialophora verrucosa",          commonName: "Cromoblastomicose",             category: "fungi" },
  { name: "Exophiala jeanselmei",           commonName: "Feohifomicose",                 category: "fungi" },
  { name: "Madurella mycetomatis",          commonName: "Micetoma eumicótico",           category: "fungi" },
  { name: "Trichophyton rubrum",            commonName: "Tinea pedis / unguium",         category: "fungi" },
  { name: "Trichophyton tonsurans",         commonName: "Tinea capitis",                 category: "fungi" },
  { name: "Microsporum canis",              commonName: "Tinea capitis / corporis",      category: "fungi" },
  { name: "Epidermophyton floccosum",       commonName: "Tinea cruris",                  category: "fungi" },
  { name: "Malassezia furfur",              commonName: "Pitiríase versicolor",          category: "fungi" },
  { name: "Lacazia loboi",                  commonName: "Lobomicose",                    category: "fungi" },

  // ── Bacteria ──────────────────────────────────────────────────────────────
  { name: "Mycobacterium tuberculosis",     commonName: "Tuberculose",                   category: "bacteria" },
  { name: "Mycobacterium leprae",           commonName: "Hanseníase",                    category: "bacteria" },
  { name: "Mycobacterium avium complex",    commonName: "Micobacteriose atípica (MAC)",  category: "bacteria" },
  { name: "Mycobacterium kansasii",         commonName: "Micobacteriose atípica",        category: "bacteria" },
  { name: "Mycobacterium abscessus",        commonName: "Micobacteriose de crescimento rápido", category: "bacteria" },
  { name: "Mycobacterium chelonae",         commonName: "Micobacteriose de crescimento rápido", category: "bacteria" },
  { name: "Mycobacterium fortuitum",        commonName: "Micobacteriose de crescimento rápido", category: "bacteria" },
  { name: "Staphylococcus aureus",          commonName: "Infecção estafilocócica / MRSA", category: "bacteria" },
  { name: "Staphylococcus epidermidis",     commonName: "Infecção por SCN",              category: "bacteria" },
  { name: "Streptococcus pneumoniae",       commonName: "Pneumonia pneumocócica",        category: "bacteria" },
  { name: "Streptococcus pyogenes",         commonName: "Faringite / erisipela / escarlatina", category: "bacteria" },
  { name: "Streptococcus agalactiae",       commonName: "Infecção por estreptococo grupo B", category: "bacteria" },
  { name: "Enterococcus faecalis",          commonName: "Enterococose",                  category: "bacteria" },
  { name: "Enterococcus faecium",           commonName: "Enterococose / VRE",            category: "bacteria" },
  { name: "Escherichia coli",               commonName: "Infecção urinária / sepse",     category: "bacteria" },
  { name: "Klebsiella pneumoniae",          commonName: "Pneumonia / sepse (KPC)",       category: "bacteria" },
  { name: "Pseudomonas aeruginosa",         commonName: "Infecção hospitalar",           category: "bacteria" },
  { name: "Acinetobacter baumannii",        commonName: "Infecção hospitalar multirresistente", category: "bacteria" },
  { name: "Stenotrophomonas maltophilia",   commonName: "Infecção oportunista",          category: "bacteria" },
  { name: "Burkholderia cepacia",           commonName: "Infecção em fibrose cística",   category: "bacteria" },
  { name: "Haemophilus influenzae",         commonName: "Meningite / pneumonia",         category: "bacteria" },
  { name: "Neisseria meningitidis",         commonName: "Meningite meningocócica",       category: "bacteria" },
  { name: "Neisseria gonorrhoeae",          commonName: "Gonorreia",                     category: "bacteria" },
  { name: "Listeria monocytogenes",         commonName: "Listeriose",                    category: "bacteria" },
  { name: "Clostridioides difficile",       commonName: "Colite pseudomembranosa",       category: "bacteria" },
  { name: "Clostridium perfringens",        commonName: "Gangrena gasosa",               category: "bacteria" },
  { name: "Nocardia brasiliensis",          commonName: "Nocardiose",                    category: "bacteria" },
  { name: "Nocardia asteroides",            commonName: "Nocardiose",                    category: "bacteria" },
  { name: "Actinomyces israelii",           commonName: "Actinomicose",                  category: "bacteria" },
  { name: "Treponema pallidum",             commonName: "Sífilis",                       category: "bacteria" },
  { name: "Borrelia burgdorferi",           commonName: "Doença de Lyme",               category: "bacteria" },
  { name: "Leptospira interrogans",         commonName: "Leptospirose",                  category: "bacteria" },
  { name: "Rickettsia rickettsii",          commonName: "Febre maculosa",               category: "bacteria" },
  { name: "Bartonella henselae",            commonName: "Doença da arranhadura do gato", category: "bacteria" },
  { name: "Brucella melitensis",            commonName: "Brucelose",                     category: "bacteria" },
  { name: "Yersinia pestis",                commonName: "Peste",                         category: "bacteria" },
  { name: "Salmonella typhi",               commonName: "Febre tifoide",                 category: "bacteria" },
  { name: "Salmonella enteritidis",         commonName: "Salmonellose",                  category: "bacteria" },
  { name: "Shigella dysenteriae",           commonName: "Disenteria bacilar",            category: "bacteria" },
  { name: "Vibrio cholerae",                commonName: "Cólera",                        category: "bacteria" },
  { name: "Campylobacter jejuni",           commonName: "Gastroenterite",                category: "bacteria" },
  { name: "Helicobacter pylori",            commonName: "Úlcera péptica / gastrite",     category: "bacteria" },
  { name: "Corynebacterium diphtheriae",    commonName: "Difteria",                      category: "bacteria" },
  { name: "Coxiella burnetii",              commonName: "Febre Q",                       category: "bacteria" },

  // ── Parasites ─────────────────────────────────────────────────────────────
  { name: "Plasmodium falciparum",          commonName: "Malária (forma grave)",          category: "parasite" },
  { name: "Plasmodium vivax",               commonName: "Malária vivax",                  category: "parasite" },
  { name: "Plasmodium malariae",            commonName: "Malária quartã",                 category: "parasite" },
  { name: "Plasmodium ovale",               commonName: "Malária ovale",                  category: "parasite" },
  { name: "Plasmodium knowlesi",            commonName: "Malária knowlesi",               category: "parasite" },
  { name: "Leishmania braziliensis",        commonName: "Leishmaniose muccocutânea",      category: "parasite" },
  { name: "Leishmania donovani",            commonName: "Calazar / Leishmaniose visceral", category: "parasite" },
  { name: "Leishmania infantum",            commonName: "Leishmaniose visceral",          category: "parasite" },
  { name: "Leishmania major",               commonName: "Leishmaniose cutânea",           category: "parasite" },
  { name: "Trypanosoma cruzi",              commonName: "Doença de Chagas",              category: "parasite" },
  { name: "Trypanosoma brucei",             commonName: "Doença do sono",               category: "parasite" },
  { name: "Toxoplasma gondii",              commonName: "Toxoplasmose",                  category: "parasite" },
  { name: "Cryptosporidium parvum",         commonName: "Criptosporidiose",              category: "parasite" },
  { name: "Giardia duodenalis",             commonName: "Giardíase",                     category: "parasite" },
  { name: "Entamoeba histolytica",          commonName: "Amebíase",                      category: "parasite" },
  { name: "Naegleria fowleri",              commonName: "Meningoencefalite amebiana primária", category: "parasite" },
  { name: "Acanthamoeba spp.",              commonName: "Ceratite amebiana / encefalite", category: "parasite" },
  { name: "Balamuthia mandrillaris",        commonName: "Encefalite amebiana granulomatosa", category: "parasite" },
  { name: "Trichomonas vaginalis",          commonName: "Tricomoníase",                  category: "parasite" },
  { name: "Strongyloides stercoralis",      commonName: "Estrongiloidíase",              category: "parasite" },
  { name: "Ascaris lumbricoides",           commonName: "Ascaridíase",                   category: "parasite" },
  { name: "Trichuris trichiura",            commonName: "Tricuríase",                    category: "parasite" },
  { name: "Ancylostoma duodenale",          commonName: "Ancilostomíase",                category: "parasite" },
  { name: "Necator americanus",             commonName: "Ancilostomíase",                category: "parasite" },
  { name: "Toxocara canis",                 commonName: "Larva migrans visceral",        category: "parasite" },
  { name: "Enterobius vermicularis",        commonName: "Oxiuríase",                     category: "parasite" },
  { name: "Taenia solium",                  commonName: "Teníase / neurocisticercose",   category: "parasite" },
  { name: "Taenia saginata",                commonName: "Teníase",                       category: "parasite" },
  { name: "Echinococcus granulosus",        commonName: "Hidatidose",                    category: "parasite" },
  { name: "Schistosoma mansoni",            commonName: "Esquistossomose",               category: "parasite" },
  { name: "Schistosoma haematobium",        commonName: "Esquistossomose urogenital",    category: "parasite" },
  { name: "Wuchereria bancrofti",           commonName: "Filariose / elefantíase",       category: "parasite" },
  { name: "Brugia malayi",                  commonName: "Filariose",                     category: "parasite" },
  { name: "Onchocerca volvulus",            commonName: "Oncocercose / cegueira dos rios", category: "parasite" },
  { name: "Loa loa",                        commonName: "Loíase",                        category: "parasite" },
  { name: "Microsporidia spp.",             commonName: "Microsporidiose",               category: "parasite" },
  { name: "Babesia microti",                commonName: "Babesiose",                     category: "parasite" },
  { name: "Isospora belli",                 commonName: "Isosporidiose",                 category: "parasite" },

  // ── Vírus (referência) ────────────────────────────────────────────────────
  { name: "Cytomegalovirus (CMV)",          commonName: "Citomegalovirose",              category: "virus" },
  { name: "Herpes simplex virus 1",         commonName: "Herpes labial / encefalite",   category: "virus" },
  { name: "Herpes simplex virus 2",         commonName: "Herpes genital",               category: "virus" },
  { name: "Varicella-zoster virus",         commonName: "Varicela / herpes-zóster",     category: "virus" },
  { name: "Epstein-Barr virus (EBV)",       commonName: "Mononucleose infecciosa",      category: "virus" },
  { name: "Adenovirus",                     commonName: "Infecção adenoviral",           category: "virus" },
  { name: "Human papillomavirus (HPV)",     commonName: "Condiloma / neoplasia cervical", category: "virus" },
  { name: "Molluscum contagiosum virus",    commonName: "Molusco contagioso",            category: "virus" },
];
